security:
    providers:
        users:
            memory:
                users: []

    firewalls:
        main:
            anonymous: ~
            logout: ~
            guard:
                authenticators:
                    - App\Security\TokenAuthenticator
            stateless: true

    access_control:
        - { path: '^/', roles: IS_AUTHENTICATED_FULLY }
