version: '2'

services:
    php:
        build:
            context: ./
            dockerfile: ./docker/php/Dockerfile
        volumes:
            - .:/app
        working_dir: /app
        ports:
            - 8081:8080
        environment:
            - APP_ENV=dev
            - PORT=8080
