version: '2'

services:
    php:
        build:
            context: ./
            dockerfile: ./docker/php/Dockerfile
        volumes:
            - .:/app
        working_dir: /app
        ports:
            - 8081:8080
        env_file:
            - .env
            - .env.local

    grafana:
        image: grafana/grafana
        environment:
            - GF_INSTALL_PLUGINS=grafana-simple-json-datasource
        ports:
            - 3000:3000
