version: '2'

services:
    php:
        build:
            context: ./
            dockerfile: ./docker/php/Dockerfile
        volumes:
            - .:/app
        working_dir: /app
        ports:
            - 8081:8080
        env_file:
            - .env
            - .env.local

    grafana:
        build:
            context: ./
            dockerfile: ./docker/grafana/Dockerfile
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=ChangeMe
            - GF_INSTALL_PLUGINS=grafana-simple-json-datasource
            - GF_AUTH_ANONYMOUS_ENABLED=true
        ports:
            - 3000:3000
