dispatch_command:
    path: /commands
    methods: POST
    controller: App\Controller\CommandController::dispatch

dispatch_query:
    path: /queries
    methods: POST
    controller: App\Controller\QueryController::dispatch
